### ISSUE TITLE
Ngrok session time out

### ISSUE THREAD

**Issue by danielhenning570** [monzo/response#10]
Need to sign up to ngrok and get a authentication token in order to extend the ngrok sessions past 7 hours.

Anyway to add the authentication token into this?

Thanks.

**Comment by AshleyPoole** [comment]
Looking at the image used for Ngrok and how it's configured [gtriggiano/ngrok-tunnel](https://github.com/gtriggiano/ngrok-tunnel/blob/master/index.js#L31), it looks like setting the environment variable called `NGROK_TOKEN` would work. You'd just need to add this to the docker-compose file to set the variable.

**Comment by evnsio** [comment]
Yep, as Ashley says, you can provide that token.  I may look at moving this container to localtunnel soon as it allows you to specify a fixed url.  Ngroks random urls are a bit annoying when you're bringing the containers up and down regularly.
