### ISSUE TITLE
Question: Action Items

### ISSUE THREAD

**Issue by AshleyPoole** [monzo/response#11]
In the demo video, I saw action items was an option but I don't think it's in the public code base. Is this something that will be made available at a later date @evnsio?

**Comment by evnsio** [comment]
Yes!  It's on my to-do list 🙂 🔜

**Comment by AshleyPoole** [comment]
Updating based on recent PRs - As of PR #43 action items can now be recorded from within the incident but UI is awaiting updates to display the action items.

**Comment by milesbxf** [comment]
@AshleyPoole I'm going to close this - we still need to update the UI to show action items, but that's now being tracked in #89 👍
