### ISSUE TITLE
Regarding Access

### ISSUE THREAD

**Issue by dwarkab** [monzo/response#123]
Hello Sir,

i remove rights of Inventory>>Transfer Save/Edit to Inventory Operator user who is only view Transfer. On main Screen Create/Edit button is not showing but if i click on any Transfer under list of that Validate/Print/Cancel buttons showing and if i click on that buttons attached error occurred.
![Screenshot from 2019-09-03 14-25-01](https://user-images.githubusercontent.com/53464253/64161920-0f44f000-ce5c-11e9-80bb-910329853348.png)

attached error message showing on click for Validate/Print/Cancel

I need to only view Transfer to Inventory Operator . if i give full access of this program operator not able to view Validate/Print button.

**Comment by milesbxf** [comment]
@dwarkab this is the wrong repository - this is response, not odoo
