### ISSUE TITLE
MySQL and timelines

### ISSUE THREAD

**Issue by sysboy** [monzo/response#132]
Hi, 

Is it possible to do some if/else magic around the JSONField timeline option that has just been added. As it currently stands I have to patch in django_mysql to get it to talk to MySQL.

I've included `django_mysql,` and replaced a few import lines like this:
```
#import django.contrib.postgres.fields.jsonb
from django_mysql.models import JSONField
```

I have nothing against postgres, I just wanted to shove this lot into the shared mysql instance I have running in gcp. It doesn't really make sense to create a total new postgres instance for it.

Cheers
   Steve

**Comment by milesbxf** [comment]
Hey @sysboy, my apologies - this was a poor choice in retrospect.

As it happens, I'm running into similar issues but with SQLite (which we use for unit tests). I merged a PR earlier today (https://github.com/monzo/response/pull/128) which changes `django.contrib.postgres.fields.JSONField` to use `JSONField` from https://github.com/dmkoch/django-jsonfield, which has support for all databases. I'm not sure exactly how this is represented in MySQL.

We're planning to do another release today or tomorrow - I'll ping you again on this issue once that's out so you can upgrade, which should hopefully solve this problem.

**Comment by milesbxf** [comment]
@sysboy we released a couple of new versions with the fix - let me know if those work for you, and we can close this
