### ISSUE TITLE
Code formatting/linting

### ISSUE THREAD

**Issue by danpalmer** [monzo/response#133]
I've been playing around with the codebase and implemented a few changes. As a newcomer to the codebase it's a little tricky to understand what the expectation of code formatting/style is.

What do the maintainers think of implementing tools such as Black for code formatting, isort for import sorting, and/or flake8 for linting? In my experience these tools make it clearer what's expected of contributors, aid readability for all, can catch bugs with some of the more interesting flake8 plugins, and can make code review more about architecture/design than style.

If the maintainers are interested in this I'm happy to have a stab at the config/implementation of this in CI, at least to start a discussion over the specifics.

**Comment by milesbxf** [comment]
Totally agree, and I've had this on the radar for a while. I use Black locally, but I'd love to have this enforced on CI. I think your suggestions of Black, isort & flake8 sound good. It probably makes sense to add this as a non-enforced check to start with, then look at formatting the whole codebase and fixing other issues - what do you reckon? Feel free to have a go at this!

**Comment by danpalmer** [comment]
Thanks. You raise a valid point about adding as a non-enforced check, but most of the strictness will come from Black which will be formatting full files anyway. I find non-enforced checks tend to get ignored more, so I'd be keen to fix up the style across the codebase and enforce, and then just maintain that as new formatting configuration changes come along.

**Comment by danpalmer** [comment]
Addressed by #135
