### ISSUE TITLE
What is the 'action' command supposed to do?

### ISSUE THREAD

**Issue by naeriaf** [monzo/response#144]
A more detailed description of the `@incident` commands would be really useful 🙏 I haven't been able to figure out what `@incident action [action_command]` is supposed to achieve 🤔 
![image](https://user-images.githubusercontent.com/37282013/64750497-3cd11e00-d56d-11e9-8a61-86f1de423404.png)

Thanks 🌻

**Comment by marcosnils** [comment]
Hey @naeriaf response user here. It actually adds an `action item` entity to the database, but the current code here doesn't show it anywhere.  We have a fork in our company where I've changed the incident document to show this information like this: 

![image](https://user-images.githubusercontent.com/1578458/65054802-8c846080-d944-11e9-9fb2-d0b9d8a18da6.png)

https://github.com/zeit/response

**Comment by naeriaf** [comment]
Thanks for that @marcosnils !! 🎉 super useful 😊
