### ISSUE TITLE
[Suggestion] - Try to avoid fault releases?

### ISSUE THREAD

**Issue by marcosnils** [monzo/response#183]
@mattrco I'm aware that you're trying to do faster releases so the project doesn't stale, but for us, consumers it creates a lot of overhead to keep up. Specially if you're finding regressions and cutting sometimes 2 o 3 releases in a day. If you see some other open source projects, that's not the case. 

Have you considered publishing the release after testing the system in your platform for some time? Otherwise, I find it super difficult for `response` users to keep up.

**Comment by mattrco** [comment]
Appreciate the frustration, we went through a period of rapid re-writing to meet internal goals and quality fell as a result. We're working on a better release process.
