### ISSUE TITLE
Feature. DB parameters with env vars

### ISSUE THREAD

**Issue by Dgadavin** [monzo/response#19]
First of all want to say thank you for such wonderful tool. Its really awesome tool to manage incidents. 

Small feature request. 
Want to setup you tool to AWS and want to use RDS. Can you please add DB_HOST, DB_PORT, DB_USER and DB_PASSWORD as env parameter?

**Comment by evnsio** [comment]
Thanks for the feedback.  I'll address this 🔜

**Comment by AshleyPoole** [comment]
@Dgadavin please see PR #24 to see if this addresses your requirements.
