### ISSUE TITLE
Feature Request: Ability to close incident from channel

### ISSUE THREAD

**Issue by AshleyPoole** [monzo/response#28]
Requesting feature to be able to close an incident from within the channel. I.e `@incident close`.

This would help as then the incident lead or engineers wouldn't have to switch back to the incidents channel in order to close the incident.

**Comment by evnsio** [comment]
We have this in our internal version, and plan to add it into Response very soon (we're in the process of migrating to the open source one)
![image](https://user-images.githubusercontent.com/6616412/59495178-a8c8bb00-8e86-11e9-970c-458944b31ed5.png)

**Comment by AshleyPoole** [comment]
I think this is resolved now by #43 @evnsio @adamlphillips?

**Comment by milesbxf** [comment]
Yep! Thanks for raising 🙌
