### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by AshleyPoole** [monzo/response#50]
Hi,

I'm seeing a strange issue whereby messages are being processed by Response multiple times.

For example, when closing an incident, it successfully closes the incident, they very quickly after also get a message about it already being closed -- which appears a few times actually, but spaced out by a minute or so.

The same duplicate behaviour happens with the `@incident help` command as well. Over the course of a minute, you get three `help` replies back.

Not sure if this is something I'm doing wrong, but as a test, I re-installed the bot within Slack to get a new token to ensure it wasn't an issue of multiple instances of Response processing the same message. Any ideas?

**Comment by AshleyPoole** [comment]
Screenshot of examples.

![2019-07-07 10_12_55-Slack - AshleyPoole](https://user-images.githubusercontent.com/3891630/60766412-53f11c80-a0a1-11e9-9f6d-16b660d33459.png)
![2019-07-07 10_13_26-Slack - AshleyPoole](https://user-images.githubusercontent.com/3891630/60766413-53f11c80-a0a1-11e9-99b4-b55e94ef228c.png)

**Comment by AshleyPoole** [comment]
From the close incident screenshot, looking in the web requests, I can see two web requests received (POSTS) for that exact time. I'm wondering if this isn't an issue with Response and maybe something with the Ngrok replacement i'm using (Cloudflare Argo Tunnel) or maybe Slack?

```
response_1  | [07/Jul/2019 09:11:26] "POST /slack/event HTTP/1.1" 200 0
response_1  | [07/Jul/2019 09:11:26] "POST /slack/event HTTP/1.1" 200 0 
```

**Comment by AshleyPoole** [comment]
I was having some weird build issues earlier when I was trying to build on Windows but now i'm on OSX  and have been able to build on a NIX OS, I can confirm using Ngrok I don't see this issue. Must be something to do with the Ngrok replacement I was using then. I'll close out.

**Comment by AshleyPoole** [comment]
I found the retries of Argo tunnel were responsible for the duplicate requests being sent. I am however still seeing the incident closed and then the incident already closed message. Can someone else confirm this is a general issue?

**Comment by evnsio** [comment]
I'm not seeing this when using ngrok, but I've seen it before when using localtunnel.  The reason you'll see this is because your app isn't responding to slack within the 3 second time limit.  Slack then assumes you didn't get the event and resends it.  

More details [here](https://api.slack.com/events-api#responding_to_events)

> Your app should respond to the event request with an HTTP 2xx within three seconds. If it does not, we'll consider the event delivery attempt failed. After a failure, we'll retry three times, backing off exponentially.
