### ISSUE TITLE
Close vs Resolve UI text

### ISSUE THREAD

**Issue by AshleyPoole** [monzo/response#52]
From the headline post, "resolve" is used for the button text but from within the incident the command is `@incident close`. Do we need to standardise on the language used or are these two events and maybe a resolve item should be added as an incident command?

![2019-07-07 10_39_45-Slack - AshleyPoole](https://user-images.githubusercontent.com/3891630/60766583-91ef4000-a0a3-11e9-86b4-25e7fd1ff145.png)

![2019-07-07 10_39_24-Slack - AshleyPoole](https://user-images.githubusercontent.com/3891630/60766584-91ef4000-a0a3-11e9-9216-1f97b1394db9.png)

**Comment by evnsio** [comment]
Have you made that change on your fork?  I believe it's 'close' everywhere in this repo :-) 

![image](https://user-images.githubusercontent.com/6616412/60836710-31085a80-a1be-11e9-8d01-3c07c1b780cc.png)

**Comment by AshleyPoole** [comment]
Sorry about the confusion, you're correct.
