### ISSUE TITLE
Bot User Not Invited to Incident Comms Channel

### ISSUE THREAD

**Issue by philovivero** [monzo/response#79]
Exact same issue as "too many channels" is "too many users."

https://github.com/philovivero/response/commit/5260f401f60b002efc84b43f68eb3d20601a4ed0#diff-1a2d815092cbb92582aa1e1107a106b8R179

In that commit is the fix. Exactly like channels, you gotta cursor through it when there are too many users.

**Comment by milesbxf** [comment]
@philovivero great spot - would you mind raising a PR with the cursor fix? 🙏

**Comment by philovivero** [comment]
PR submitted, and I hear it'll get merged.
