### ISSUE TITLE
Usage without ngrok

### ISSUE THREAD

**Issue by lol768** [monzo/response#9]
Is this just a case of removing these lines and setting up a reverse proxy on the machine to point at port 8000 on the `response` container?

https://github.com/monzo/response/blob/97e35de75cd78eb3b6cd4db0a2b3f99a5ce582c8/docker-compose.yaml#L40-L47

**Comment by evnsio** [comment]
Yes, that would be fine. 

You shouldn't even need to remove that though. The response container is accessible on localhost:8000 so you can stick whatever you like in front of it.
